### ISSUE TITLE
The requested platform 'eWeLink' was not registered by any plugin. v 1.5.5

### ISSUE THREAD

**Issue by isax5** [thepotterfamily/homebridge-ewelink-sonoff#3]
**What issue do you have?**
There is a problem in the last updated

**Which version of the package are you using?**
1.5.5
**Please paste any relevant logs below**
`[7/5/2020, 09:06:54] Error: The requested platform 'eWeLink' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/5/2020, 09:06:54] Got SIGTERM, shutting down Homebridge...
[7/5/2020, 09:06:59] [HB Supervisor] Homebridge Process Ended. Code:`
...

**Comment by isax5** [comment]
New logs:
`[7/5/2020, 09:10:52] ====================
[7/5/2020, 09:10:52] ERROR LOADING PLUGIN homebridge-ewelink-sonoff:
[7/5/2020, 09:10:52] Error: Cannot find module './src/constants'
Require stack:
- /usr/local/lib/node_modules/homebridge-ewelink-sonoff/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-sonoff/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
[7/5/2020, 09:10:52] ====================`

**Comment by thepotterfamily** [comment]
hi, thanks for alerting me of this. please try the new update. i made a stupid error 👎

**Comment by isax5** [comment]
It's working correctly
